/**
 * F22 — Individual User PDF Health Summary
 *
 * Renders a print-ready personal health report in a new window.
 * Contains: BHAS v1 score, BHAS v2.3 score, per-marker breakdown,
 * national benchmark comparisons.
 *
 * No PDF library needed — browser "Save as PDF" via window.open() + print CSS.
 * PHI compliance: report is self-generated by the user for their own use only.
 */

import { useRef } from 'react'
import { type BhasResult, type MarkerScore } from '../utils/evaluateRules'
import { type BhasV2Result } from '../utils/bhasV2'
import { type UserLabResult } from '../context/ResultsContext'
import { getBenchmark } from '../utils/nationalBenchmarks'

interface Props {
  userName: string
  publicId: string | null
  bhasResult: BhasResult | null
  bhasV2Result: BhasV2Result | null
  results: UserLabResult[]
  onClose: () => void
  theme: any
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function scoreColor(label: string): string {
  if (label === 'Optimal') return '#15803d'
  if (label === 'Improvement') return '#b45309'
  return '#b91c1c'
}

function v2LabelColor(label: string): string {
  if (label === 'Optimal') return '#15803d'
  if (label === 'Healthy') return '#1d4ed8'
  if (label === 'Needs Improvement') return '#b45309'
  return '#b91c1c'
}

function optRangeLabel(b: { optimalMin: number; optimalMax: number; unit: string }): string {
  if (b.optimalMax >= 999) return `≥ ${b.optimalMin} ${b.unit}`
  if (b.optimalMin === 0) return `< ${b.optimalMax} ${b.unit}`
  return `${b.optimalMin}–${b.optimalMax} ${b.unit}`
}

// ── Print HTML builder ────────────────────────────────────────────────────────

function buildPrintHtml(props: Omit<Props, 'onClose' | 'theme'>): string {
  const { userName, publicId, bhasResult, bhasV2Result, results } = props
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  // Deduplicate to latest value per marker
  const latestByMarker = results.reduce<Record<string, UserLabResult>>((acc, r) => {
    if (!acc[r.markerName] || r.date > acc[r.markerName].date) acc[r.markerName] = r
    return acc
  }, {})
  const latestResults = Object.values(latestByMarker)

  // Per-marker BHAS rows (v1)
  const markerRows = bhasResult?.markerScores.map((ms: MarkerScore) => {
    const r = latestByMarker[ms.markerName]
    return `
      <tr>
        <td>${ms.markerName}</td>
        <td style="text-align:right">${r ? `${r.value} ${r.unit}` : '—'}</td>
        <td style="text-align:center;color:${scoreColor(ms.label)};font-weight:600">${ms.label}</td>
        <td style="text-align:center;font-weight:700;color:${ms.score === 1 ? '#15803d' : ms.score === 0.5 ? '#b45309' : '#b91c1c'}">${ms.score === 1 ? '1.0' : ms.score === 0.5 ? '0.5' : '0.0'}</td>
      </tr>`
  }).join('') ?? '<tr><td colspan="4" style="text-align:center;color:#6b7280">No scored markers yet.</td></tr>'

  // BHAS v2.3 metric rows
  const v2Rows = bhasV2Result?.metricScores
    .filter(m => m.included)
    .map(m => `
      <tr>
        <td>${m.metric}</td>
        <td style="text-align:center;color:#374151">${m.derived}</td>
        <td style="text-align:center;color:${scoreColor(m.label)};font-weight:600">${m.label}</td>
        <td style="text-align:center;font-weight:700;color:${m.score === 1 ? '#15803d' : m.score === 0.5 ? '#b45309' : '#b91c1c'}">${m.score === 1 ? '1.0' : m.score === 0.5 ? '0.5' : '0.0'}</td>
      </tr>`).join('') ?? '<tr><td colspan="4" style="text-align:center;color:#6b7280">Insufficient data for v2.3 scoring.</td></tr>'

  // National benchmark rows
  const benchmarkRows = latestResults
    .map(r => ({ r, b: getBenchmark(r.markerName) }))
    .filter(({ b }) => b !== null)
    .map(({ r, b }) => {
      const diff = r.value - b!.nationalMean
      const isBetter = b!.lowerIsBetter ? diff <= 0 : diff >= 0
      const pct = b!.nationalMean !== 0 ? Math.abs(Math.round((diff / b!.nationalMean) * 100)) : 0
      const arrow = b!.lowerIsBetter ? (diff < 0 ? '↓' : diff > 0 ? '↑' : '—') : (diff > 0 ? '↑' : diff < 0 ? '↓' : '—')
      const isOptimal = b!.lowerIsBetter ? r.value <= b!.optimalMax : r.value >= b!.optimalMin
      const color = isBetter ? '#15803d' : '#b91c1c'
      return `
        <tr>
          <td>${r.markerName}</td>
          <td style="text-align:right;font-weight:700">${r.value} ${r.unit}</td>
          <td style="text-align:right;color:#6b7280">${b!.nationalMean} ${b!.unit}</td>
          <td style="text-align:center;color:${color};font-weight:700">${arrow} ${pct > 0 ? `${pct}%` : 'At avg'}</td>
          <td style="text-align:center;color:${isOptimal ? '#15803d' : '#b91c1c'};font-size:11px">${isOptimal ? 'Optimal' : 'Below optimal'} · ${optRangeLabel(b!)}</td>
        </tr>`
    }).join('') || '<tr><td colspan="5" style="text-align:center;color:#6b7280">No markers with national benchmark data.</td></tr>'

  const bhasPct = bhasResult ? `${bhasResult.percentage}%` : '—'
  const bhasLabel = bhasResult && bhasResult.maxPossible > 0
    ? `${bhasResult.totalScore.toFixed(1)} / ${bhasResult.maxPossible.toFixed(1)}`
    : '—'

  const v2Score = bhasV2Result?.hasEnoughData ? `${bhasV2Result.totalScore.toFixed(2)} / 7.00` : '—'
  const v2Label = bhasV2Result?.hasEnoughData ? bhasV2Result.label : '—'
  const v2LabelC = bhasV2Result?.hasEnoughData ? v2LabelColor(bhasV2Result.label) : '#374151'

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>NHL Personal Health Report — ${today}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 40px; color: #111; font-size: 13px; line-height: 1.5; }
    h1 { font-size: 22px; font-weight: 800; margin: 0 0 2px 0; }
    h2 { font-size: 15px; font-weight: 700; margin: 24px 0 8px 0; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; color: #111; }
    p { margin: 0 0 6px 0; color: #6b7280; font-size: 12px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 8px; font-size: 12px; }
    th { background: #f9fafb; border: 1px solid #e5e7eb; padding: 7px 10px; font-weight: 600; text-align: left; color: #374151; }
    td { border: 1px solid #e5e7eb; padding: 7px 10px; color: #111; }
    .score-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 4px; }
    .score-card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 14px 18px; }
    .score-value { font-size: 28px; font-weight: 800; margin-bottom: 2px; }
    .score-sub { font-size: 12px; color: #6b7280; }
    .score-label { font-size: 13px; font-weight: 700; margin-top: 4px; }
    .disclaimer { font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 10px; margin-top: 20px; }
    @media print {
      body { margin: 20px; }
      button { display: none; }
    }
  </style>
</head>
<body>

  <h1>National Health League — Personal Health Report</h1>
  <p style="font-size:13px;color:#374151;margin-bottom:2px">
    <strong>Member:</strong> ${userName || '(username not set)'}
    ${publicId ? `&nbsp;·&nbsp; <strong>ID:</strong> ${publicId}` : ''}
  </p>
  <p style="margin-bottom:18px">Report Date: ${today} &nbsp;·&nbsp; For personal use only — contains your private health data</p>

  <button
    onclick="window.print()"
    style="background:#3B82F6;color:#fff;border:none;border-radius:6px;padding:9px 20px;font-size:13px;font-weight:600;cursor:pointer;margin-bottom:20px"
  >
    Save as PDF / Print
  </button>

  <!-- BHAS Score Summary -->
  <h2>BHAS Score Summary</h2>
  <div class="score-grid">
    <div class="score-card">
      <div class="score-sub">BHAS v1 Score (marker-based)</div>
      <div class="score-value" style="color:#1d4ed8">${bhasPct}</div>
      <div class="score-sub">${bhasLabel} markers scored</div>
    </div>
    <div class="score-card">
      <div class="score-sub">BHAS v2.3 Score (ratio-based)</div>
      <div class="score-value" style="color:${v2LabelC}">${v2Score}</div>
      <div class="score-label" style="color:${v2LabelC}">${v2Label}</div>
    </div>
  </div>

  <!-- Per-Marker BHAS v1 Breakdown -->
  <h2>Per-Marker Breakdown (BHAS v1)</h2>
  <table>
    <thead>
      <tr>
        <th>Marker</th>
        <th style="text-align:right">Your Value</th>
        <th style="text-align:center">Status</th>
        <th style="text-align:center">Score</th>
      </tr>
    </thead>
    <tbody>${markerRows}</tbody>
  </table>

  <!-- BHAS v2.3 Metric Breakdown -->
  <h2>BHAS v2.3 Metric Breakdown</h2>
  <p>Derived ratio scoring — max 9.0 points across 9 metrics.</p>
  <table>
    <thead>
      <tr>
        <th>Metric</th>
        <th style="text-align:center">Derived Value</th>
        <th style="text-align:center">Status</th>
        <th style="text-align:center">Score</th>
      </tr>
    </thead>
    <tbody>${v2Rows}</tbody>
  </table>
  ${bhasV2Result && bhasV2Result.missingInputs.length > 0
    ? `<p style="color:#b45309;font-size:12px;margin-top:4px">Missing inputs: ${bhasV2Result.missingInputs.join(', ')}</p>`
    : ''}

  <!-- National Benchmarks -->
  <h2>National Benchmarks (CDC/NHANES)</h2>
  <p>Your latest values vs. U.S. adult population averages.</p>
  <table>
    <thead>
      <tr>
        <th>Marker</th>
        <th style="text-align:right">Your Value</th>
        <th style="text-align:right">US Average</th>
        <th style="text-align:center">vs. National Avg</th>
        <th style="text-align:center">Optimal Range</th>
      </tr>
    </thead>
    <tbody>${benchmarkRows}</tbody>
  </table>
  <p style="font-size:11px;color:#9ca3af">Sources: CDC NHANES 2017–2020 · AHA/ACC 2019 · ADA 2024 · NIH/NLM</p>

  <div class="disclaimer">
    This report is generated for personal reference only. It is not a medical diagnosis or clinical recommendation.
    Consult a licensed healthcare provider before making changes to your health regimen.
    National Health League does not share this report with employers, insurers, or third parties.
  </div>

</body>
</html>`
}

// ── Modal ─────────────────────────────────────────────────────────────────────

export default function HealthReportModal({ userName, publicId, bhasResult, bhasV2Result, results, onClose, theme }: Props) {
  const hasData = (bhasResult && bhasResult.maxPossible > 0) || (bhasV2Result?.hasEnoughData)

  function handlePrint() {
    const html = buildPrintHtml({ userName, publicId, bhasResult, bhasV2Result, results })
    const w = window.open('', '_blank', 'width=900,height=750')
    if (!w) return
    w.document.write(html)
    w.document.close()
  }

  const overlay: React.CSSProperties = {
    position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)',
    display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000,
  }
  const modal: React.CSSProperties = {
    background: theme.card, border: `1.5px solid ${theme.borderColor}`,
    borderRadius: 12, padding: '28px 32px', width: 480, maxWidth: '95vw',
    boxShadow: '0 8px 32px rgba(0,0,0,0.18)',
  }

  return (
    <div style={overlay} onClick={e => { if (e.target === e.currentTarget) onClose() }}>
      <div style={modal}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 }}>
          <h3 style={{ margin: 0, fontSize: 17, fontWeight: 700, color: theme.text }}>Personal Health Report</h3>
          <button
            onClick={onClose}
            style={{ background: 'none', border: 'none', fontSize: 20, cursor: 'pointer', color: theme.textMuted, lineHeight: 1 }}
          >
            ×
          </button>
        </div>

        <p style={{ margin: '0 0 20px 0', fontSize: 13, color: theme.textMuted, lineHeight: 1.6 }}>
          Generates a printable personal health summary containing your BHAS scores,
          per-marker breakdown, and national benchmark comparisons. Use your browser's
          "Save as PDF" option to download.
        </p>

        {!hasData && (
          <div style={{
            background: theme.bgSecondary, border: `1px solid ${theme.borderColor}`,
            borderRadius: 8, padding: '12px 16px', marginBottom: 20,
            fontSize: 13, color: theme.textMuted,
          }}>
            Log lab results to generate a scored health report.
          </div>
        )}

        <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end' }}>
          <button
            onClick={onClose}
            style={{
              background: theme.bgSecondary, color: theme.text,
              border: `1px solid ${theme.borderColor}`, borderRadius: 8,
              padding: '9px 18px', fontSize: 13, fontWeight: 600, cursor: 'pointer',
            }}
          >
            Cancel
          </button>
          <button
            onClick={handlePrint}
            disabled={!hasData}
            style={{
              background: hasData ? '#3B82F6' : theme.bgSecondary,
              color: hasData ? '#fff' : theme.textMuted,
              border: 'none', borderRadius: 8,
              padding: '9px 20px', fontSize: 13, fontWeight: 600,
              cursor: hasData ? 'pointer' : 'default',
              transition: 'background 0.2s',
            }}
          >
            Open Report
          </button>
        </div>
      </div>
    </div>
  )
}
